---
- name: Hosts prepare
  hosts: molecule
  gather_facts: false
  tasks:

    - name: Hosts prepare. Get OS ID from /etc/*release
      ansible.builtin.raw: |
        grep -m1 '^ID=' /etc/*release | cut -d= -f2 | tr -d '"\r\n'
      args:
        executable: /bin/bash
      register: os_id
      changed_when: os_id.rc != 0

    - name: Hosts prepare. Install Python3 on Debian/Ubuntu/Alpine
      ansible.builtin.raw: |
        apt update && apt install -y sudo python3 python3-apt aptitude
      args:
        executable: /bin/bash
      when: os_id.stdout == "ubuntu" or os_id.stdout == "debian" or os_id.stdout == "alpine"

    - name: Hosts prepare. Install Python3 on CentOS
      ansible.builtin.raw: |
        sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        yum clean all && yum makecache && yum update -y
        yum install -y sudo python39
      args:
        executable: /bin/bash
      when: os_id.stdout == "centos"

    - name: Hosts prepare. Install Python3 on OEL
      ansible.builtin.raw: |
        yum clean all && yum makecache && yum update -y
        yum install -y sudo python3
      args:
        executable: /bin/bash
      when: os_id.stdout == "ol"

    - name: Hosts prepare. Install Python3 on RedHat/Fedora
      ansible.builtin.raw: |
        dnf clean all && dnf makecache && dnf update -y
        dnf install -y sudo python3
      args:
        executable: /bin/bash
      when: os_id.stdout == "fedora"
